#!/bin/sh

python <<HEREDOC |
import glob, os, re

search_dirs = [
    os.path.expanduser('~/.local/share/applications'),
    '/usr/local/share/applications',
    '/usr/share/applications'
]

def get_term(pid, halt=False):
    with open('/proc/%s/stat' % pid, 'r') as stat:
        info = stat.read().split(' ')

    exe = info[1].strip('()')
    ppid = info[3]

    if halt:
        return os.readlink('/proc/%s/exe' % pid)
    else:
        return get_term(ppid, exe == current_shell)

current_shell = os.path.basename(os.getenv('SHELL', ''))
term = get_term(os.getpid())


FMT_RE = re.compile(r'\s?%.')

def read_desktop_entry(fh):
    values = {}

    has_section = False
    for line in fh.readlines():
        line = line.strip()

        if not line:
            continue

        if line == '[Desktop Entry]':
            has_section = True
        elif line[0] == '[':
            if has_section:
                break
        else:
            kv = line.split('=', 1)

            if len(kv) > 1:
                values[kv[0]] = kv[1]

    if values.get('NoDisplay', '') != 'true':
        name = values.get('Name', '')
        execute = FMT_RE.sub('', values.get('Exec', ''))

        if values.get('Terminal', '') == 'true':
            execute = '%s -e %s -c %s' % (term, current_shell, execute)

        return '%s;%s' % (execute, name)
    else:
        return None

parsed_entries = []

for search_dir in search_dirs:
    for file in glob.glob('%s/**.desktop' % search_dir):
        entry_name = os.path.basename(file)

        if entry_name in parsed_entries:
            continue

        with open(file, 'r', encoding='utf-8') as fh:
            if entry := read_desktop_entry(fh):
                print(entry)

        parsed_entries.append(entry_name)
HEREDOC
fzf --layout=reverse --no-info -d\; --with-nth=2 --nth=1 | cut -d\; -f1
