#!/bin/sh

battery_level_fn() {
    BAT_dir=/sys/class/power_supply/$1

    charge_now=$(cat ${BAT_dir}/energy_now)
    charge_full=$(cat ${BAT_dir}/energy_full)

    echo "scale=2;(${charge_now}/${charge_full})*100" | bc | cut -d. -f1
}

charging_fn() {
    AC_dir=/sys/class/power_supply/AC
    indicator=$1

    AC_online=$(cat ${AC_dir}/online)

    if [ "${AC_online}" == "1" ]; then
        echo $indicator
    else
        echo " "
    fi
}

battery_level_critical_fn() {
    level=`battery_level_fn $1`
    threshold=$2

    if [ $level -le $threshold ]; then
        echo true
    else
        echo false
    fi
}

wifi_wpa_cli_ssid_fn() {
    interface=$1
    wpa_cli -p "${interface}" status | grep ^ssid= | cut -d= -f2
}

wifi_signal_strength_fn() {
    interface=$1
    worst_rssi=-85
    perfect_rssi=-20

    current_rssi=$(cat /proc/net/wireless | grep $interface | tr -s ' ' | tr -d '.' | cut -d' ' -f4)

    nr=$(( $perfect_rssi - $worst_rssi ))
    dr=$(( $perfect_rssi - $current_rssi ))

    quality=$(( $(( 100 * $nr * $nr - $dr * $(( 15 * $nr + 62 * $dr )) )) / $(( $nr * $nr )) ))

    echo "${quality}%"
}

date_fn() {
    date "+%m/%d %H:%M"
}

freemem_fn() {
    cat /proc/meminfo | \
        grep MemAvailable | tr -s ' ' | cut -d' ' -f2 \
        | xargs -I {} echo 'scale=1; {}/1024^2' | bc
}

updates_avail=0
next_update_check=0

get_updates() {
    current_time=$(date +%s)

    if [ ${current_time} -gt ${next_update_check} ]; then
        updates_avail=$(($(pacman -Qu | wc -l)))
        next_update_check=$(($current_time + 3600))
    fi
}

has_updates() {
    if [ $updates_avail -gt 0 ]; then
        echo "true"
    else
        echo "false"
    fi
}

get_updates_() {
    last_upgrade_time=$(grep "\[PACMAN\] starting full system upgrade" /var/log/pacman.log | tail -1 | grep -oP '\[\K[^\]]+' | head -1)
    last_upgrade_utime=$(date '+%s' -d "$last_upgrade_time")
    current_utime=$(date '+%s')

    time_diff=$(( $current_utime - $last_upgrade_utime ))
    day_diff=$(( $time_diff / 86400 ))
    hour_diff=$(( ($time_diff - 86400 * $day_diff) / 3600 ))

    if [ $day_diff -gt 0 ]; then
        updates_avail=$(($(pacman -Qu | wc -l)))

        msg="Last update: $day_diff days, $hour_diff hours (${updates_avail} packages to update)"
    else
        msg="System up to date"
    fi

    echo $msg
}

function format() {
    content="$1"
    urgent="${2:-false}"
    width="${3:-100}"
    align="${4:-center}"

    cat << JSON
    {
        "full_text": "${content}",
        "urgent": "${urgent}",
        "background": "#e5e9f0",
        "color": "#434c5e",
        "min_width": ${width},
        "align": "${align}",
        "border_top": 0,
        "border_bottom": 0,
        "border_left": 0,
        "border_right": 0,
        "separator_block_width": 2,
        "separator": false
    }
JSON
}

echo '{ "version": 1 }'
echo '['

while :; do
    get_updates
cat << JSON
[
$(format "$(freemem_fn)G" false 80),
$(format "$(wifi_wpa_cli_ssid_fn /run/wpa_supplicant) ($(wifi_signal_strength_fn wlp3s0))" false 200),
$(format "$(battery_level_fn BAT0)%$(charging_fn "~")" "$(battery_level_critical_fn BAT0 10)" 60),
$(format "${updates_avail}" "$(has_updates)" 50),
$(format "$(date_fn)" false 130)
],
JSON
    sleep 1
done
