#!/bin/sh

battery_level_fn() {
    BAT_dir=/sys/class/power_supply/$1

    charge_now=$(cat ${BAT_dir}/energy_now)
    charge_full=$(cat ${BAT_dir}/energy_full)

    echo "scale=2;(${charge_now}/${charge_full})*100" | bc | cut -d. -f1
}

charging_fn() {
    AC_dir=/sys/class/power_supply/AC
    indicator=$1

    AC_online=$(cat ${AC_dir}/online)

    if [ "${AC_online}" == "1" ]; then
        echo $indicator
    else
        echo " "
    fi
}

battery_level_critical_fn() {
    level=`battery_level_fn $1`
    threshold=$2

    if [ $level -le $threshold ]; then
        echo true
    else
        echo false
    fi
}

wifi_wpa_cli_ssid_fn() {
    interface=$1
    wpa_cli -p "${interface}" status | grep ^ssid= | cut -d= -f2
}

wifi_signal_strength_fn() {
    interface=$1
    worst_rssi=-85
    perfect_rssi=-20

    current_rssi=$(cat /proc/net/wireless | grep $interface | tr -s ' ' | tr -d '.' | cut -d' ' -f4)

    nr=$(( $perfect_rssi - $worst_rssi ))
    dr=$(( $perfect_rssi - $current_rssi ))

    quality=$(( $(( 100 * $nr * $nr - $dr * $(( 15 * $nr + 62 * $dr )) )) / $(( $nr * $nr )) ))

    echo "${quality}%"
}

date_fn() {
    date "+%m/%d %H:%M"
}

freemem_fn() {
    cat /proc/meminfo | \
        grep MemAvailable | tr -s ' ' | cut -d' ' -f2 \
        | xargs -I {} echo 'scale=1; {}/1024^2' | bc
}

window_fn() {
    # Blocking, do not use
    swaymsg -t subscribe -m '["window"]' | jq -r '.container.name'
}

function format() {
    echo -n "{\"full_text\":\"${1}\"},"
}

echo '{ "version": 1 }'
echo '['

while :; do
cat << JSON
[
    {
        "full_text": "$(freemem_fn)G"
    },
    {
        "full_text": "$(wifi_wpa_cli_ssid_fn /run/wpa_supplicant) ($(wifi_signal_strength_fn wlp3s0))"
    },
    {
        "full_text": "$(battery_level_fn BAT0)%$(charging_fn "~")",
        "urgent": $(battery_level_critical_fn BAT0 10)
    },
    {
        "full_text": "$(date_fn)"
    }
],
JSON
    sleep 1
done
