#!/bin/sh

gpg-connect-agent updatestartuptty /bye

profile="mailbox"

MAILDIR="${HOME}/.local/mail/${profile}"

[ ! -d "${MAILDIR}" ] && mkdir -p "${MAILDIR}"

mbsync -c $XDG_CONFIG_HOME/mbsync/mbsyncrc -R ${profile}
